# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('icon', models.ImageField(null=True, upload_to='article')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
