# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=200)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
